version = 1

[install]
stow.pkg-path = "stow"
bat.pkg-path = "bat"
eza.pkg-path = "eza"
zoxide.pkg-path = "zoxide"
difftastic.pkg-path = "difftastic"
universal-ctags.pkg-path = "universal-ctags"
ripgrep.pkg-path = "ripgrep"
go-task.pkg-path = "go-task"
jq.pkg-path = "jq"
fastfetch.pkg-path = "fastfetch"
hyperfine.pkg-path = "hyperfine"
fd.pkg-path = "fd"
jemalloc.pkg-path = "jemalloc"
xh.pkg-path = "xh"
xan.pkg-path = "xan"
ast-grep.pkg-path = "ast-grep"
cloc.pkg-path = "cloc"
tree-sitter.pkg-path = "tree-sitter"

[options]
systems = ["x86_64-linux"]
